version: '3'
networks:
  my-network:
    driver: bridge
services:
  app:
    container_name: katrusya-api-container
    networks:
      - my-network
    build: .
    ports:
      - '3000:3000'
    depends_on:
      db:
       condition: service_healthy   
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: MoSalah
      DB_PASSWORD: qwerty123
      DB_NAME: katrusya
    command: bash -c "npm run db:rollback && npm run db:migrate && npm run db:seed && npm run start:dev"  

  db:
    container_name: katrusya-db-container
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      retries: 10
    networks:
      - my-network
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zoom123123
      MYSQL_USER: MoSalah
      MYSQL_PASSWORD: qwerty123
      MYSQL_DATABASE: katrusya
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3037:3037'
      